# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2cb68a6f72e8c37923920b4712915374ba4f388f6f5322fd4a2b51aba050c860e88ab3a6b267192a4ea1d6cc41ecdc9133537235258eb987765be723b97b2a3
  twitter_app_id: <%= File.read(File.join(Rails.root.to_s, 'config', 'twitter_consumer_key')) %>
  twitter_app_secret: <%= File.read(File.join(Rails.root.to_s, 'config', 'twitter_app_secret')) %>

test:
  secret_key_base: 6c524a32d33a9391e1774c0fc0023cca11ad7fc820c5c4bbdcc5918dcdbdb33ff152b60390b00ecd472692fdbba7e9f9af8f149941f5f6d5766c63588f7ed292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
